### ISSUE TITLE
ESLint - 希望殺死紅色蚯蚓

### ISSUE THREAD

**Issue by rainingut** [ayugioh2003/metawallBackend#27]
`globalError.js` 檔案好多紅色蚯蚓
有類似這些錯誤提示，
```
Assignment to property of function parameter 'err'.
'err.name' is assigned to itself.
Unexpected console statement.
```
請問需要增修哪些程式碼 
還是 ESLint 需要設定什麼地方嗎 😲
![](https://media.discordapp.net/attachments/954435567733575710/977561334449328188/unknown.png?width=619&height=597)

**Comment by ayugioh2003** [comment]
這個我來做好了

**Comment by ayugioh2003** [comment]
已處理
https://github.com/ayugioh2003/metawallBackend/pull/28
